repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: contrast-check
        name: Kontrastprüfung
        entry: npm --prefix theme/static_src run contrast -- base.html
        language: system
        pass_filenames: false
        exclude: ".*"

      - id: django-checks-tests
        name: Tests (makemigrations --check + pytest)
        entry: python tools/run_checks_and_tests.py
        language: system
        pass_filenames: false
        stages: [pre-commit]

