repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
  - repo: local
    hooks:
      - id: contrast-check
        name: Kontrastprüfung
        entry: npm --prefix theme/static_src run contrast -- base.html
        language: system
        pass_filenames: false
        exclude: ".*"
