# Generated by Django 5.2.4 on 2025-08-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funktionsergebnis",
            name="anlage_datei",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funktions_ergebnisse",
                to="core.bvprojectfile",
            ),
        ),
        migrations.CreateModel(
            name="GroupAreaAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.area"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "area")},
            },
        ),
        migrations.AddField(
            model_name="area",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gruppen mit Zugriff auf diesen Bereich.",
                related_name="areas",
                through="core.GroupAreaAccess",
                to="auth.group",
            ),
        ),
        migrations.CreateModel(
            name="GroupTileAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "tile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.tile"
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "tile")},
            },
        ),
        migrations.AddField(
            model_name="tile",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="tiles",
                through="core.GroupTileAccess",
                to="auth.group",
            ),
        ),
    ]
