# Generated by Django 5.2.2 on 2025-06-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="duration",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
