# Generated by Django 5.2.5 on 2025-08-27 10:36

from django.db import migrations, models


def set_auto_for_removed_mode(apps, schema_editor):
    """Setzt entfernte Parser-Modi auf den Standardwert."""
    BVProjectFile = apps.get_model("core", "BVProjectFile")
    Anlage2Config = apps.get_model("core", "Anlage2Config")
    BVProjectFile.objects.filter(parser_mode="text_only").update(parser_mode="auto")
    Anlage2Config.objects.filter(parser_mode="text_only").update(parser_mode="auto")


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_formatbparserrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anlage2config",
            name="parser_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Automatisch"),
                    ("table_only", "Nur Tabellen"),
                    ("exact_only", "Nur Exakt"),
                ],
                default="auto",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bvprojectfile",
            name="parser_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "Automatisch"),
                    ("table_only", "Nur Tabellen"),
                    ("exact_only", "Nur Exakt"),
                ],
                default="",
                help_text="Spezifischer Parser-Modus für diese Anlage.",
                max_length=20,
            ),
        ),
        migrations.RunPython(set_auto_for_removed_mode, migrations.RunPython.noop),
    ]
