# Generated by Django 5.2.4 on 2025-08-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_group_access_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="funktionsergebnis",
            name="anlage_datei",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funktions_ergebnisse",
                to="core.bvprojectfile",
            ),
        ),
    ]
