# Generated by Django 5.2.3 on 2025-07-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anlage2GlobalPhrase',
        ),
    ]
