# Generated by Django 5.2.5 on 2025-08-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_formatbparserrule"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2config",
            name="default_parser",
            field=models.CharField(
                blank=True,
                default="exact",
                help_text="Name des Standard-Parsers für Anlage 2.",
                max_length=100,
            ),
        ),
    ]
