# Generated by Django 5.2.5 on 2025-08-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_formatbparserrule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bvprojectfile",
            name="anlage_nr",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5"), (6, "6")],
                null=True,
                verbose_name="Anlage Nr",
            ),
        ),
    ]
