# Generated by Django 5.2.2 on 2025-06-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recording_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
