# Generated by Django 5.2.3 on 2025-07-01 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0003_delete_anlage2globalphrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.tile",
                verbose_name="Übergeordnete Kachel",
            ),
        ),
        migrations.AddField(
            model_name="tile",
            name="permission",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="auth.permission",
                verbose_name="Benötigte Berechtigung",
            ),
        ),
    ]
