# Generated by Django 5.2.4 on 2025-08-01 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0003_alter_funktionsergebnis_anlage_datei"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="users",
        ),
        migrations.AddField(
            model_name="area",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gruppen mit Zugriff auf diesen Bereich.",
                related_name="areas",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="tile",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gruppen mit Zugriff auf diese Kachel.",
                related_name="tiles",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="funktionsergebnis",
            name="anlage_datei",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funktions_ergebnisse",
                to="core.bvprojectfile",
            ),
        ),
        migrations.DeleteModel(
            name="UserAreaAccess",
        ),
    ]
