# Generated by Django 5.2.5 on 2025-08-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_normalize_analysis_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bvprojectfile",
            name="manual_analysis_json",
        ),
    ]
