# Generated by Django 5.2.4 on 2025-08-01 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_remove_area_users_area_groups_tile_groups_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Gruppen mit Zugriff auf diesen Bereich.",
                related_name="areas",
                through="core.GroupAreaAccess",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="tile",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="tiles",
                through="core.GroupTileAccess",
                to="auth.group",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="anlagenfunktionsmetadaten",
            unique_together={("anlage_datei", "funktion", "subquestion")},
        ),
        migrations.CreateModel(
            name="UserAreaAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.area"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "area")},
            },
        ),
    ]
