# Generated by Django 5.2.2 on 2025-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_bvproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvproject",
            name="llm_initial_output",
            field=models.TextField(blank=True, verbose_name="LLM Initialantwort"),
        ),
        migrations.AddField(
            model_name="bvproject",
            name="llm_validated",
            field=models.BooleanField(default=False, verbose_name="LLM validiert"),
        ),
    ]
