# Generated by Django 5.2.3 on 2025-07-01 18:38

from django.db import migrations


# Diese Funktion enthält unsere Logik
def grant_superuser_all_permissions(apps, schema_editor):
    """
    Sucht alle Superuser und weist ihnen alle existierenden Berechtigungen zu.
    """
    User = apps.get_model("auth", "User")
    Permission = apps.get_model("auth", "Permission")

    # 1. Alle existierenden Berechtigungen sammeln
    all_permissions = list(Permission.objects.all())

    # 2. Alle Superuser finden
    superusers = User.objects.filter(is_superuser=True)

    # 3. Jedem Superuser alle Berechtigungen zuweisen
    for user in superusers:
        user.user_permissions.set(all_permissions)
        # Optional: Eine Nachricht im Terminal ausgeben
        # print(f"\nSuperuser '{user.username}' wurden alle {len(all_permissions)} Berechtigungen zugewiesen.")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_tile_parent_tile_permission"),
        # Wichtig: Wir hängen von der auth-App ab, da wir User und Permission nutzen
        ("auth", "__latest__"),
    ]

    operations = [
        # Hier rufen wir unsere Funktion auf
        migrations.RunPython(grant_superuser_all_permissions),
    ]
