# Generated by Django 5.2.3 on 2025-07-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20250701_2038"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2function",
            name="detection_phrases",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="anlage2subquestion",
            name="detection_phrases",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
