# Generated by Django 5.2.2 on 2025-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_bvproject_llm_initial_output_bvproject_llm_validated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bvproject",
            name="title",
            field=models.CharField(blank=True, max_length=50, verbose_name="Titel"),
        ),
    ]
