# Generated by Django 5.2.4 on 2025-08-03 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_area_groups_alter_tile_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anlagenfunktionsmetadaten",
            name="anlage_datei",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.bvprojectfile",
            ),
        ),
    ]
