# Generated by Django 5.2.3 on 2025-07-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20250701_2038"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormatBParserRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=10, unique=True)),
                ("target_field", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
                ("is_boolean", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
