# Generated by Django 5.2.2 on 2025-06-06 16:08

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_bvproject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvproject",
            name="anlage1_check",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bvproject",
            name="system_classification",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BVProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=50)),
                (
                    "file",
                    models.FileField(upload_to=core.models.project_file_upload_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.bvproject",
                    ),
                ),
            ],
        ),
    ]
