# Generated by Django 5.2.2 on 2025-06-06 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_bvproject_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="BVProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anlage_nr",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                        ],
                        verbose_name="Anlage Nr",
                    ),
                ),
                (
                    "upload",
                    models.FileField(upload_to="bv_files", verbose_name="Upload"),
                ),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Textinhalt"),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anlagen",
                        to="core.bvproject",
                    ),
                ),
            ],
            options={
                "ordering": ["anlage_nr"],
            },
        ),
    ]
