# Generated by Django 5.2.2 on 2025-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_bvproject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Neu"),
                    ("classified", "Klassifiziert"),
                    ("gutachten_ok", "Gutachten OK"),
                    ("rejected", "Abgelehnt"),
                ],
                default="new",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
