# Generated by Django 5.2.4 on 2025-08-04 13:31

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_anlagenfunktionsmetadaten_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anlage2config",
            name="parser_order",
            field=models.JSONField(
                default=core.models.Anlage2Config.default_parser_order,
                help_text="Reihenfolge der zu verwendenden Parser.",
            ),
        ),
    ]
