# Generated by Django 5.2.4 on 2025-08-04 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_anlagenfunktionsmetadaten_unique"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bvsoftware",
            old_name="projekt",
            new_name="project",
        ),
    ]
