# Generated by Django 5.2.3 on 2025-07-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_anlage2function_detection_phrases_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntwortErkennungsRegel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("regel_name", models.CharField(max_length=100)),
                ("erkennungs_phrase", models.CharField(max_length=200)),
                (
                    "ziel_feld",
                    models.CharField(
                        choices=[
                            ("technisch_verfuegbar", "Technisch verfügbar"),
                            ("einsatz_telefonica", "Einsatz Telefónica"),
                            ("zur_lv_kontrolle", "Zur LV-Kontrolle"),
                            ("ki_beteiligung", "KI-Beteiligung"),
                        ],
                        max_length=50,
                    ),
                ),
                ("wert", models.BooleanField()),
                ("prioritaet", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["prioritaet"],
            },
        ),
    ]
