# Generated by Django 5.2.2 on 2025-06-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_bvproject_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvproject",
            name="classification_json",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Klassifizierung"
            ),
        ),
        migrations.AddField(
            model_name="bvproject",
            name="gutachten_file",
            field=models.FileField(
                blank=True, upload_to="gutachten", verbose_name="Gutachten"
            ),
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="analysis_json",
            field=models.JSONField(blank=True, null=True, verbose_name="Analyse"),
        ),
    ]
