# Generated by Django 5.2.3 on 2025-07-03 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_antworterkennungsregel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage4Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_columns", models.JSONField(blank=True, default=list)),
                ("regex_patterns", models.JSONField(blank=True, default=list)),
                ("negative_patterns", models.JSONField(blank=True, default=list)),
                ("prompt_template", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Anlage4 Konfiguration",
            },
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="anlage4_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.anlage4config",
            ),
        ),
    ]
