# Generated by Django 5.2 on 2025-06-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_bvproject_classification_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="manual_comment",
            field=models.TextField(blank=True, verbose_name="Kommentar"),
        ),
    ]
