# Generated by Django 5.2.4 on 2025-08-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_bvsoftware_project"),
    ]

    operations = [
        migrations.RenameField(
            model_name="softwareknowledge",
            old_name="projekt",
            new_name="project",
        ),
    ]
