# Generated by Django 5.2.4 on 2025-07-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_anlage4_parser_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anlage4parserconfig",
            name="text_rules",
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="fachbereich_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="gesellschaft_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="name_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="negative_patterns",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
