# Generated by Django 5.2.4 on 2025-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_anlage4_parser_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anlage4parserconfig",
            name="text_rules",
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="delimiter_phrase",
            field=models.CharField(
                default="Name der (\\d+|\\w+)\\. Auswertung",
                help_text="Regulärer Ausdruck, der den Beginn einer neuen Auswertung markiert.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="fachbereiche_phrase",
            field=models.CharField(
                default="Fachbereiche, in denen die Auswertung eingesetzt wird:",
                help_text="Die exakte Phrase, die dem Wert für 'Fachbereiche' vorangeht.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="gesellschaften_phrase",
            field=models.CharField(
                default="Gesellschaften, in denen die Auswertung verwendet wird:",
                help_text="Die exakte Phrase, die dem Wert für 'Gesellschaften' vorangeht.",
                max_length=255,
            ),
        ),
    ]
