# Generated by Django 5.2 on 2025-06-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_bvproject_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="manual_analysis_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
