# Generated by Django 5.2.4 on 2025-07-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_update_parser_config_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="fachbereich_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="gesellschaft_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="name_aliases",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage4parserconfig",
            name="negative_patterns",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
