# Generated by Django 5.2.4 on 2025-08-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_anlage2config_parser_order"),
        ("core", "0008_rename_projekt_bvsoftware_project"),
        ("core", "0011_rename_funktionsergebnis_project"),
    ]

    operations = []
