# Generated by Django 5.2 on 2025-06-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_bvprojectfile_manual_analysis_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("text", models.TextField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
