# Generated by Django 5.2.4 on 2025-07-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_add_alias_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anlage4parserconfig",
            name="prompt_extraction",
        ),
    ]
