# Generated by Django 5.2.3 on 2025-07-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_anlage4parserconfig_prompt_extraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2functionresult",
            name="gap_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="anlage2functionresult",
            name="is_negotiable",
            field=models.BooleanField(default=False),
        ),
    ]
