# Generated by Django 5.2 on 2025-06-06 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_prompt_model"),
    ]

    def create_prompts(apps, schema_editor):
        Prompt = apps.get_model("core", "Prompt")
        prompts = {
            "classify_system": (
                "Bitte klassifiziere das folgende Softwaresystem. Gib ein JSON mit den Schl\u00fcsseln 'kategorie' und 'begruendung' zur\u00fcck.\n\n"
            ),
            "generate_gutachten": (
                "Erstelle ein kurzes Gutachten basierend auf diesen Unterlagen:\n\n"
            ),
            "generate_overall_gutachten": (
                "Erstelle ein zusammenfassendes Gutachten f\u00fcr das Projekt '{project_title}'. Ber\u00fccksichtige alle folgenden Software-Komponenten und deren Analyseergebnisse: {context_data}. Fasse die Ergebnisse zusammen, bewerte das Gesamtprojekt und gib eine Abschlussempfehlung ab. Strukturiere das Gutachten mit klaren \u00dcberschriften und formatiere es mit Markdown (z.B. \u00dcberschriften, Fett- und Kursivdruck, Listen und Tabellen)."
            ),
        }
        for i in range(1, 7):
            if i == 2:
                continue
            prompts[f"check_anlage{i}"] = (
                "Pr\u00fcfe die folgende Anlage auf Vollst\u00e4ndigkeit. Gib ein JSON mit 'ok' und 'hinweis' zur\u00fcck:\n\n"
            )
        for name, text in prompts.items():
            Prompt.objects.get_or_create(name=name, defaults={"text": text})

    operations = [migrations.RunPython(create_prompts, migrations.RunPython.noop)]
