# Generated by Django 5.2.2 on 2025-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_default_prompts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bvproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "Neu"),
                    ("CLASSIFIED", "Klassifiziert"),
                    ("GUTACHTEN_OK", "Gutachten OK"),
                    ("GUTACHTEN_FREIGEGEBEN", "Gutachten freigegeben"),
                    ("IN_PRUEFUNG_ANLAGE_X", "In Prüfung Anlage X"),
                    ("FB_IN_PRUEFUNG", "FB in Prüfung"),
                    ("ENDGEPRUEFT", "Endgeprüft"),
                ],
                default="NEW",
                max_length=30,
                verbose_name="Status",
            ),
        ),
    ]
