# Generated by Django 5.2.4 on 2025-07-11 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_add_project_prompt"),
        ("core", "0014_anlage2functionresult_gap_summary_and_more"),
    ]

    operations = []
