# Generated by Django 5.2.2 on 2025-06-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_bvproject_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("default_model", models.CharField(blank=True, max_length=100)),
                ("gutachten_model", models.CharField(blank=True, max_length=100)),
                ("anlagen_model", models.CharField(blank=True, max_length=100)),
                ("available_models", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "LLM Konfiguration",
            },
        ),
    ]
