# Generated by Django 5.2 on 2025-07-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_anlage2functionresult_result_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="verification_task_id",
            field=models.CharField(
                blank=True,
                help_text="ID des laufenden Verifizierungstasks.",
                max_length=50,
            ),
        ),
    ]
