# Generated by Django 5.2.2 on 2025-06-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_llmconfig_models_changed"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bereich",
                    models.CharField(
                        choices=[("personal", "personal"), ("work", "work")],
                        max_length=10,
                    ),
                ),
                ("url_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("icon", models.CharField(max_length=50)),
                (
                    "bg_class",
                    models.CharField(
                        default="bg-gradient-to-r from-purple-600 to-purple-800",
                        max_length=100,
                    ),
                ),
                ("admin_only", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
