from django.db import migrations

# Generated by Django to add Standard-Kacheln


def create_tiles(apps, schema_editor):
    Tile = apps.get_model("core", "Tile")
    Tile.objects.get_or_create(
        bereich="personal",
        url_name="talkdiary_personal",
        defaults={
            "title": "TalkDiary",
            "description": "Sprachaufzeichnungen & Transkripte",
            "icon": "fas fa-book",
            "bg_class": "bg-gradient-to-r from-purple-600 to-purple-800",
        },
    )
    Tile.objects.get_or_create(
        bereich="work",
        url_name="talkdiary_work",
        defaults={
            "title": "TalkDiary",
            "description": "Sprachaufzeichnungen & Transkripte",
            "icon": "fas fa-book",
            "bg_class": "bg-gradient-to-r from-purple-600 to-purple-800",
        },
    )
    Tile.objects.get_or_create(
        bereich="work",
        url_name="projekt_list",
        defaults={
            "title": "Projektverwaltung",
            "description": "Betriebsvereinbarungen",
            "icon": "fas fa-folder-open",
            "bg_class": "bg-gradient-to-r from-green-600 to-green-800",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_tile"),
    ]

    operations = [
        migrations.RunPython(create_tiles, migrations.RunPython.noop),
    ]
