# Generated by Django 5.2.2 on 2025-06-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_tile_usertileaccess_tile_users"),
    ]

    def create_tiles(apps, schema_editor):
        Tile = apps.get_model("core", "Tile")
        tiles = [
            {
                "slug": "talkdiary",
                "name": "TalkDiary",
                "bereich": "personal",
                "url_name": "talkdiary_personal",
            },
            {
                "slug": "projektverwaltung",
                "name": "Projektverwaltung",
                "bereich": "work",
                "url_name": "projekt_list",
            },
        ]
        for data in tiles:
            Tile.objects.get_or_create(slug=data["slug"], defaults=data)

    operations = [migrations.RunPython(create_tiles, migrations.RunPython.noop)]
