# Generated by Django 5.2.4 on 2025-07-14 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_bvprojectfile_verification_task_id"),
        ("core", "0018_zweckkategoriea"),
    ]

    operations = []
