# Generated by Django 5.2.4 on 2025-07-13 22:48

from django.db import migrations, models


def seed_zweckkategoriea(apps, schema_editor):
    """Füllt die Tabelle ZweckKategorieA mit Standardwerten."""
    ZweckKategorieA = apps.get_model("core", "ZweckKategorieA")
    ZweckKategorieA.objects.bulk_create(
        [
            ZweckKategorieA(
                beschreibung="Leistungsvergleiche von Mitarbeitern oder Mitarbeitergruppen (wenn eine der Gruppen nicht größer als 5 Personen ist)."
            ),
            ZweckKategorieA(
                beschreibung="Abgleich von Verhalten oder Leistung eines Mitarbeiters oder einer Mitarbeitergruppe (wenn eine der Gruppen nicht größer als 5 Personen ist) mit bestimmten Durchschnittsleistungen von Mitarbeitergruppen."
            ),
            ZweckKategorieA(
                beschreibung="Messung der Qualität oder Quantität der Leistung eines Mitarbeiters oder von Kenntnissen oder Fähigkeiten, um das Ergebnis der Messung mit einem Sollwert oder Vorgaben (z. B. betriebliche Ziele) abzugleichen."
            ),
            ZweckKategorieA(beschreibung="Messung der Auslastung von Mitarbeitern."),
            ZweckKategorieA(
                beschreibung="Feststellung der vergangenheitsbezogenen Termine bzw. Erreichbarkeit oder persönlichen Verfügbarkeit eines Mitarbeiters."
            ),
            ZweckKategorieA(
                beschreibung="Feststellung der Termine bzw. Erreichbarkeit oder persönlichen Verfügbarkeit des Mitarbeiters in Echtzeit."
            ),
            ZweckKategorieA(
                beschreibung="Feststellung der zukünftigen Termine bzw. Erreichbarkeit oder persönlichen Verfügbarkeit des Mitarbeiters in Echtzeit."
            ),
            ZweckKategorieA(
                beschreibung="Erstellung von Bewertungen von Leistung oder Verhalten von Mitarbeitern (z. B. Zeugnisse, Scorecards etc.)."
            ),
            ZweckKategorieA(
                beschreibung="Identifikation von Mitarbeitern nach bestimmten Skills (Kenntnisse, Fähigkeiten und Erfahrungen)."
            ),
            ZweckKategorieA(beschreibung="Erstellung von Persönlichkeitsprofilen."),
            ZweckKategorieA(
                beschreibung="Ermittlung des aktuellen Arbeitsortes/Aufenthaltsortes."
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_bvprojectfile_verification_task_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZweckKategorieA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beschreibung", models.TextField()),
            ],
            options={
                "verbose_name": "Zweck Kategorie A",
                "verbose_name_plural": "Zwecke Kategorie A",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(seed_zweckkategoriea, reverse_code=migrations.RunPython.noop),
    ]
