# Generated by Django 5.2.2 on 2025-06-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_seed_tiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="tile",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: seed_icons(apps),
            migrations.RunPython.noop,
        ),
    ]


def seed_icons(apps):
    Tile = apps.get_model("core", "Tile")
    defaults = {
        "talkdiary": {
            "icon": "fas fa-book",
            "description": "Sprachaufzeichnungen & Transkripte",
        },
        "projektverwaltung": {
            "icon": "fas fa-folder-open",
            "description": "Betriebsvereinbarungen",
        },
    }
    for slug, data in defaults.items():
        try:
            tile = Tile.objects.get(slug=slug)
            for field, value in data.items():
                setattr(tile, field, value)
            tile.save(update_fields=list(data))
        except Tile.DoesNotExist:
            continue
