# Generated by Django 5.2.4 on 2025-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_zweckkategoriea"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2config",
            name="text_einsatz_telefonica_false",
            field=models.JSONField(
                default=list, help_text="Phrasen für Einsatz bei Telefónica = Nein"
            ),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_einsatz_telefonica_true",
            field=models.JSONField(
                default=list, help_text="Phrasen für Einsatz bei Telefónica = Ja"
            ),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_ki_beteiligung_false",
            field=models.JSONField(
                default=list, help_text="Phrasen für KI-Beteiligung = Nein"
            ),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_ki_beteiligung_true",
            field=models.JSONField(
                default=list, help_text="Phrasen für KI-Beteiligung = Ja"
            ),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_technisch_verfuegbar_false",
            field=models.JSONField(
                default=list, help_text="Phrasen für technisch verfügbar = Nein"
            ),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_zur_lv_kontrolle_false",
            field=models.JSONField(
                default=list, help_text="Phrasen für zur LV-Kontrolle = Nein"
            ),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_zur_lv_kontrolle_true",
            field=models.JSONField(
                default=list, help_text="Phrasen für zur LV-Kontrolle = Ja"
            ),
        ),
        migrations.AlterField(
            model_name="anlage2config",
            name="text_technisch_verfuegbar_true",
            field=models.JSONField(
                default=list, help_text="Phrasen für technisch verfügbar = Ja"
            ),
        ),
    ]
