# Generated by Django 5.2 on 2025-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_anlage2config_text_einsatz_telefonica_false_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2functionresult",
            name="einsatz_bei_telefonica",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="anlage2functionresult",
            name="zur_lv_kontrolle",
            field=models.BooleanField(null=True),
        ),
    ]
