# Generated by Django 5.2 on 2025-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_tile_description_tile_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="question_review",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
