# Generated by Django 5.2.4 on 2025-07-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_anlage2functionresult_einsatz_bei_telefonica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2functionresult",
            name="gap_notiz",
            field=models.TextField(blank=True, null=True),
        ),
    ]
