# Generated by Django 5.2.2 on 2025-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_update_check_anlage1_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage1Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_q1", models.BooleanField(default=True)),
                ("enable_q2", models.BooleanField(default=True)),
                ("enable_q3", models.BooleanField(default=True)),
                ("enable_q4", models.BooleanField(default=True)),
                ("enable_q5", models.BooleanField(default=True)),
                ("enable_q6", models.BooleanField(default=True)),
                ("enable_q7", models.BooleanField(default=True)),
                ("enable_q8", models.BooleanField(default=True)),
                ("enable_q9", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Anlage1 Konfiguration",
            },
        ),
        migrations.RunPython(
            lambda apps, schema_editor: [
                apps.get_model("core", "Prompt").objects.get_or_create(
                    name=f"anlage1_q{i}",
                    defaults={"text": text},
                )
                for i, text in enumerate(
                    [
                        "Frage 1: Extrahiere alle Unternehmen als Liste.",
                        "Frage 2: Extrahiere alle Fachbereiche als Liste.",
                        "Frage 3: Liste alle Hersteller und Produktnamen auf.",
                        "Frage 4: Lege den Textblock als question4_raw ab.",
                        "Frage 5: Fasse den Zweck des Systems in einem Satz.",
                        "Frage 6: Extrahiere Web-URLs.",
                        "Frage 7: Extrahiere ersetzte Systeme.",
                        "Frage 8: Extrahiere Legacy-Funktionen.",
                        "Frage 9: Lege den Text als question9_raw ab.",
                    ],
                    start=1,
                )
            ],
            migrations.RunPython.noop,
        ),
    ]
