# Generated by Django 5.2.3 on 2025-07-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_add_gap_notiz_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="antworterkennungsregel",
            name="regel_anwendungsbereich",
            field=models.CharField(
                choices=[
                    ("Hauptfunktion", "Hauptfunktion"),
                    ("Unterfrage", "Unterfrage"),
                ],
                default="Hauptfunktion",
                max_length=20,
            ),
        ),
    ]
