# Generated by Django 5.2.2 on 2025-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_update_check_anlage1_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage1Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_q1", models.BooleanField(default=True)),
                ("enable_q2", models.BooleanField(default=True)),
                ("enable_q3", models.BooleanField(default=True)),
                ("enable_q4", models.BooleanField(default=True)),
                ("enable_q5", models.BooleanField(default=True)),
                ("enable_q6", models.BooleanField(default=True)),
                ("enable_q7", models.BooleanField(default=True)),
                ("enable_q8", models.BooleanField(default=True)),
                ("enable_q9", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Anlage1 Konfiguration",
            },
        ),
    ]
