# Generated by Django 5.2.4 on 2025-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_add_regel_anwendungsbereich"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2functionresult",
            name="is_negotiable_override",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
