# Generated by Django 5.2 on 2025-06-08 12:39

from django.db import migrations, models

DEFAULT_QUESTIONS = [
    "Frage 1: Extrahiere alle Unternehmen als Liste.",
    "Frage 2: Extrahiere alle Fachbereiche als Liste.",
    "Frage 3: Liste alle Hersteller und Produktnamen auf.",
    "Frage 4: Lege den Textblock als question4_raw ab.",
    "Frage 5: Fasse den Zweck des Systems in einem Satz.",
    "Frage 6: Extrahiere Web-URLs.",
    "Frage 7: Extrahiere ersetzte Systeme.",
    "Frage 8: Extrahiere Legacy-Funktionen.",
    "Frage 9: Lege den Text als question9_raw ab.",
]


def seed_questions(apps, schema_editor):
    Question = apps.get_model("core", "Anlage1Question")
    for i, text in enumerate(DEFAULT_QUESTIONS, start=1):
        Question.objects.create(num=i, text=text, enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_anlage1config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage1Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num", models.PositiveSmallIntegerField(unique=True)),
                ("text", models.TextField()),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["num"],
            },
        ),
        migrations.RunPython(seed_questions, migrations.RunPython.noop),
    ]
