# Generated by Django 5.2.2 on 2025-06-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_anlage1question"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage1question",
            name="llm_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="anlage1question",
            name="parser_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
