# Generated by Django 5.2.4 on 2025-07-17 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_rename_negotiable_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage5Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sonstige_zwecke", models.TextField(blank=True)),
                (
                    "found_purposes",
                    models.ManyToManyField(blank=True, to="core.zweckkategoriea"),
                ),
                (
                    "project_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anlage5review",
                        to="core.bvprojectfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anlage 5 Review",
                "verbose_name_plural": "Anlage 5 Reviews",
            },
        ),
    ]
