# Generated by Django 5.2 on 2025-06-09 00:00
from django.db import migrations


def create_prompt(apps, schema_editor):
    Prompt = apps.get_model('core', 'Prompt')
    Prompt.objects.get_or_create(
        name='anlage1_email',
        defaults={'text': 'Formuliere eine freundliche E-Mail an den Fachbereich. Bitte fasse die folgenden Vorschl\u00e4ge zusammen:\n\n'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_copy_enabled_flags'),
    ]

    operations = [
        migrations.RunPython(create_prompt, migrations.RunPython.noop),
    ]
