# Generated by Django 5.2 on 2025-06-08 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_anlage1_email_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="BVProjectStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Neu"),
                            ("CLASSIFIED", "Klassifiziert"),
                            ("GUTACHTEN_OK", "Gutachten OK"),
                            ("GUTACHTEN_FREIGEGEBEN", "Gutachten freigegeben"),
                            ("IN_PRUEFUNG_ANLAGE_X", "In Prüfung Anlage X"),
                            ("FB_IN_PRUEFUNG", "FB in Prüfung"),
                            ("ENDGEPRUEFT", "Endgeprüft"),
                        ],
                        max_length=30,
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.bvproject",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at"],
            },
        ),
    ]
