# Generated by Django 5.2.4 on 2025-07-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_add_anlage2_prompts"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="anlage6_note",
            field=models.TextField(blank=True, verbose_name="Prüfnotiz"),
        ),
    ]
