# Generated by Django 5.2 on 2025-06-09 14:32

import django.db.models.deletion
from django.db import migrations, models


def seed_variants(apps, schema_editor):
    Question = apps.get_model("core", "Anlage1Question")
    Variant = apps.get_model("core", "Anlage1QuestionVariant")
    for q in Question.objects.all():
        Variant.objects.create(question=q, text=q.text)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_bvprojectstatushistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage1QuestionVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="core.anlage1question",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(seed_variants, migrations.RunPython.noop),
    ]
