# Generated by Django 5.2 on 2025-07-18 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_subquestion_to_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage3Metadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("beschreibung", models.TextField(blank=True)),
                ("zeitraum", models.CharField(blank=True, max_length=100)),
                ("art", models.CharField(blank=True, max_length=100)),
                (
                    "project_file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anlage3meta",
                        to="core.bvprojectfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anlage 3 Metadaten",
                "verbose_name_plural": "Anlage 3 Metadaten",
            },
        ),
    ]
