# Generated by Django 5.2.2 on 2025-06-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_anlage1question_variants"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tile_images/"),
        ),
    ]
