# Generated by Django 5.2.4 on 2025-07-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_add_subquestion_to_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="antworterkennungsregel",
            name="actions_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Feld-Wert-Paare für den exakten Parser.",
            ),
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="parser_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("auto", "Automatisch"),
                    ("table_only", "Nur Tabellen"),
                    ("text_only", "Nur Text"),
                    ("exact_only", "Nur Exakt"),
                ],
                default="",
                help_text="Spezifischer Parser-Modus für diese Anlage.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="parser_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Reihenfolge der Parser für diese Anlage.",
            ),
        ),
        migrations.AlterField(
            model_name="anlage2config",
            name="parser_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Automatisch"),
                    ("table_only", "Nur Tabellen"),
                    ("text_only", "Nur Text"),
                    ("exact_only", "Nur Exakt"),
                ],
                default="auto",
                max_length=20,
            ),
        ),
    ]
