# Generated by Django 5.2 on 2025-07-18 21:58

from django.db import migrations, models


def seed_anlage3_parser_rules(apps, schema_editor):
    """Erzeugt die Standardregeln für Anlage 3."""
    Anlage3ParserRule = apps.get_model("core", "Anlage3ParserRule")
    Anlage3ParserRule.objects.create(
        field_name="name",
        aliases=["name der auswertung", "name", "bezeichnung"],
        ordering=1,
    )
    Anlage3ParserRule.objects.create(
        field_name="beschreibung",
        aliases=["beschreibung", "kurzbeschreibung"],
        ordering=2,
    )
    Anlage3ParserRule.objects.create(
        field_name="zeitraum",
        aliases=["zeitraum", "auswertungszeitraum"],
        ordering=3,
    )
    Anlage3ParserRule.objects.create(
        field_name="art",
        aliases=["art der auswertung", "auswertungsart", "typ"],
        ordering=4,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_anlage3_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage3ParserRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("name", "Name der Auswertung"),
                            ("beschreibung", "Beschreibung"),
                            ("zeitraum", "Zeitraum"),
                            ("art", "Art der Auswertung"),
                        ],
                        max_length=50,
                    ),
                ),
                ("aliases", models.JSONField(blank=True, default=list)),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Anlage 3 Parser Regel",
                "verbose_name_plural": "Anlage 3 Parser Regeln",
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.RunPython(seed_anlage3_parser_rules, reverse_code=migrations.RunPython.noop),
    ]
