"""Migration für ForeignKey-Beziehungen zu Area."""
# Generated by Codex

from django.db import migrations, models
import django.db.models.deletion


def create_initial_areas(apps, schema_editor):
    Area = apps.get_model('core', 'Area')
    Area.objects.get_or_create(slug='personal', defaults={'name': 'Personal'})
    Area.objects.get_or_create(slug='work', defaults={'name': 'Work'})


def migrate_bereich(apps, schema_editor):
    Area = apps.get_model('core', 'Area')
    Recording = apps.get_model('core', 'Recording')
    Tile = apps.get_model('core', 'Tile')
    areas = {a.slug: a.id for a in Area.objects.all()}
    for rec in Recording.objects.all():
        rec.bereich_fk_id = areas.get(rec.bereich) if hasattr(rec, 'bereich') and isinstance(rec.bereich, str) else rec.bereich_id
        rec.save(update_fields=['bereich_fk'])
    for tile in Tile.objects.all():
        tile.bereich_fk_id = areas.get(tile.bereich) if hasattr(tile, 'bereich') and isinstance(tile.bereich, str) else tile.bereich_id
        tile.save(update_fields=['bereich_fk'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_area'),
    ]

    operations = [
        migrations.RunPython(create_initial_areas, migrations.RunPython.noop),
        migrations.AddField(
            model_name='recording',
            name='bereich_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
        migrations.AddField(
            model_name='tile',
            name='bereich_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
        migrations.RunPython(migrate_bereich, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='recording',
            name='bereich',
        ),
        migrations.RemoveField(
            model_name='tile',
            name='bereich',
        ),
        migrations.RenameField(
            model_name='recording',
            old_name='bereich_fk',
            new_name='bereich',
        ),
        migrations.RenameField(
            model_name='tile',
            old_name='bereich_fk',
            new_name='bereich',
        ),
        migrations.AlterField(
            model_name='recording',
            name='bereich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
        migrations.AlterField(
            model_name='tile',
            name='bereich',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area'),
        ),
    ]
