# Generated by Codex
from django.db import migrations


def create_prompt(apps, schema_editor):
    Prompt = apps.get_model('core', 'Prompt')
    Prompt.objects.get_or_create(
        name='analyse_anlage2',
        defaults={
            'text': (
                'Analysiere den folgenden Text und gib eine JSON-Liste von Objekten mit den '
                "Schl\xFCsseln 'funktion', 'technisch_vorhanden', 'einsatz_bei_telefonica', "
                "'zur_lv_kontrolle' und 'ki_beteiligung' zur\n\n"
            )
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_area_fk'),
    ]

    operations = [
        migrations.RunPython(create_prompt, migrations.RunPython.noop),
    ]
