# Generated by Django 5.0.1 on 2025-07-22 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_actions_json_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anlage2functionresult",
            name="ai_result",
        ),
        migrations.RemoveField(
            model_name="anlage2functionresult",
            name="doc_result",
        ),
        migrations.RemoveField(
            model_name="anlage2functionresult",
            name="manual_result",
        ),
        migrations.RemoveField(
            model_name="anlage2functionresult",
            name="raw_json",
        ),
        migrations.CreateModel(
            name="FunktionsErgebnis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quelle", models.CharField(max_length=20)),
                ("technisch_verfuegbar", models.BooleanField(null=True)),
                ("einsatz_bei_telefonica", models.BooleanField(null=True)),
                ("zur_lv_kontrolle", models.BooleanField(null=True)),
                ("ki_beteiligung", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "funktion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.anlage2function",
                    ),
                ),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bvproject"
                    ),
                ),
                (
                    "subquestion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.anlage2subquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
