# Generated by Django 5.2.1 on 2025-06-10 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_initial_llm_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2function",
            name="einsatz_bei_telefonica",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="anlage2function",
            name="ki_beteiligung",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="anlage2function",
            name="technisch_vorhanden",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="anlage2function",
            name="zur_lv_kontrolle",
            field=models.BooleanField(null=True),
        ),
        migrations.CreateModel(
            name="Anlage2SubQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frage_text", models.TextField()),
                ("technisch_vorhanden", models.BooleanField(null=True)),
                ("einsatz_bei_telefonica", models.BooleanField(null=True)),
                ("zur_lv_kontrolle", models.BooleanField(null=True)),
                ("ki_beteiligung", models.BooleanField(null=True)),
                (
                    "funktion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.anlage2function",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
