# Generated by Django 5.2 on 2025-07-22 06:45

import django.db.models.deletion
from django.db import migrations, models


def set_anlage_datei_for_existing_results(apps, schema_editor):
    FunktionsErgebnis = apps.get_model("core", "FunktionsErgebnis")
    BVProjectFile = apps.get_model("core", "BVProjectFile")
    for res in FunktionsErgebnis.objects.all():
        pf = (
            BVProjectFile.objects.filter(projekt=res.projekt, anlage_nr=2)
            .order_by("id")
            .first()
        )
        if pf:
            res.anlage_datei_id = pf.id
            res.save(update_fields=["anlage_datei"])



class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_add_funktions_ergebnis"),
    ]

    operations = [
        migrations.AddField(
            model_name="funktionsergebnis",
            name="anlage_datei",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funktions_ergebnisse",
                to="core.bvprojectfile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="funktionsergebnis",
            name="begruendung",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RunPython(set_anlage_datei_for_existing_results, migrations.RunPython.noop),
    ]
