# Generated by Django 5.2 on 2025-06-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_anlage2function_einsatz_bei_telefonica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2functionresult",
            name="source",
            field=models.CharField(default="llm", max_length=10),
        ),
    ]
