# Generated by Django 5.2 on 2025-06-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_add_source_to_functionresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anlage2functionresult",
            name="einsatz_telefonica",
        ),
        migrations.RemoveField(
            model_name="anlage2functionresult",
            name="zur_lv_kontrolle",
        ),
    ]
