# Generated by Django 5.2.4 on 2025-07-22 18:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_rename_anlage2functionresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anlage2config",
            name="parser_order",
            field=models.JSONField(
                default=core.models.Anlage2Config.default_parser_order,
                help_text="Reihenfolge der zu verwendenden Parser.",
            ),
        ),
    ]
