# Generated by Django 5.2.1 on 2025-06-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_bvproject_gutachten_function_note'),
        ('core', '0038_remove_fields_from_functionresult'),
    ]

    operations = [
    ]
