# Generated by Django 5.2.3 on 2025-06-11 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_anlage2_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage2ColumnHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("technisch_vorhanden", "Technisch vorhanden"),
                            ("einsatz_bei_telefonica", "Einsatz bei Telefónica"),
                            ("zur_lv_kontrolle", "Zur LV-Kontrolle"),
                            ("ki_beteiligung", "KI-Beteiligung"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="core.anlage2config",
                    ),
                ),
            ],
            options={
                "ordering": ["field_name", "id"],
            },
        ),
    ]
