# Generated by Django 5.2.4 on 2025-07-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_gap_prompts_and_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlagenfunktionsmetadaten",
            name="supervisor_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
