# Generated by Django 5.2.4 on 2025-07-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_supervision_standard_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="core.bvprojectfile",
            ),
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
