# Generated by Django 5.2.3 on 2025-06-11 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_anlage2config_singleton"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anlage2config",
            name="col_einsatz_bei_telefonica",
        ),
        migrations.RemoveField(
            model_name="anlage2config",
            name="col_ki_beteiligung",
        ),
        migrations.RemoveField(
            model_name="anlage2config",
            name="col_technisch_vorhanden",
        ),
        migrations.RemoveField(
            model_name="anlage2config",
            name="col_zur_lv_kontrolle",
        ),
    ]
