# Generated by Django 5.2.3 on 2025-06-12 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_remove_anlage2config_col_einsatz_bei_telefonica_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anlage2function",
            name="einsatz_bei_telefonica",
        ),
        migrations.RemoveField(
            model_name="anlage2function",
            name="ki_beteiligung",
        ),
        migrations.RemoveField(
            model_name="anlage2function",
            name="technisch_vorhanden",
        ),
        migrations.RemoveField(
            model_name="anlage2function",
            name="zur_lv_kontrolle",
        ),
        migrations.RemoveField(
            model_name="anlage2subquestion",
            name="einsatz_bei_telefonica",
        ),
        migrations.RemoveField(
            model_name="anlage2subquestion",
            name="ki_beteiligung",
        ),
        migrations.RemoveField(
            model_name="anlage2subquestion",
            name="technisch_vorhanden",
        ),
        migrations.RemoveField(
            model_name="anlage2subquestion",
            name="zur_lv_kontrolle",
        ),
    ]
