# Generated by Django 5.2.4 on 2025-07-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_bvprojectfile_processing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="use_project_context",
            field=models.BooleanField(
                default=True,
                help_text="Soll diesem Prompt automatisch der Projekt-Kontext vorangestellt werden?",
            ),
        ),
    ]
