# Generated by Django 5.2.4 on 2025-07-27 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_add_prompt_project_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
