# Generated by Django 5.2.3 on 2025-06-12 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_remove_anlage2function_einsatz_bei_telefonica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2function",
            name="detection_phrases",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON-Objekt zur Speicherung von Erkennungsphrasen für den Text-Parser.",
            ),
        ),
        migrations.AddField(
            model_name="anlage2subquestion",
            name="detection_phrases",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON-Objekt zur Speicherung von Erkennungsphrasen für den Text-Parser.",
            ),
        ),
    ]
