# Generated by Django 5.2.3 on 2025-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_anlage2function_detection_phrases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="verification_json",
            field=models.JSONField(
                blank=True,
                help_text="Ergebnis der KI-gestützten Verifizierung der Funktionen.",
                null=True,
            ),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("core", "Prompt").objects.get_or_create(
                name="anlage2_feature_verification",
                defaults={
                    "text": (
                        "Du bist ein Experte für IT-Systeme und Software-Architektur. "
                        "Bewerte die folgende Aussage ausschließlich basierend auf deinem "
                        "allgemeinen Wissen über die Software '{software_name}'. "
                        "Antworte NUR mit \"Ja\", \"Nein\" oder \"Unsicher\". "
                        "Aussage: Besitzt die Software '{software_name}' typischerweise "
                        "die Funktion oder Eigenschaft '{function_name}'?"
                    ),
                },
            ),
            migrations.RunPython.noop,
        ),
    ]
