# Generated by Django 5.2.4 on 2025-07-28 06:58

from django.db import migrations


def forwards_func(apps, schema_editor):
    """Löscht den ungenutzten Prompt."""
    Prompt = apps.get_model("core", "Prompt")
    Prompt.objects.filter(name="anlage2_ai_involvement_justification").delete()


def reverse_func(apps, schema_editor):
    """Stellt den gelöschten Prompt wieder her."""
    Prompt = apps.get_model("core", "Prompt")
    text = (
        "Gib eine kurze Begründung, warum die Funktion '{function_name}' "
        "(oder die Unterfrage '{subquestion_text}') der Software '{software_name}' "
        "eine KI-Komponente beinhaltet oder beinhalten kann, insbesondere im "
        "Hinblick auf die Verarbeitung unstrukturierter Daten oder nicht-deterministischer "
        "Ergebnisse."
    )
    Prompt.objects.update_or_create(
        name="anlage2_ai_involvement_justification", defaults={"text": text}
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_bvprojectfile_created_at"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
