# Generated by Django 5.2.3 on 2025-06-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_bvprojectfile_verification_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage2GlobalPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phrase_type",
                    models.CharField(
                        choices=[
                            ("technisch_verfuegbar_true", "Technisch vorhanden: Ja"),
                            ("technisch_verfuegbar_false", "Technisch vorhanden: Nein"),
                            ("einsatz_telefonica_true", "Einsatz bei Telefónica: Ja"),
                            (
                                "einsatz_telefonica_false",
                                "Einsatz bei Telefónica: Nein",
                            ),
                            ("zur_lv_kontrolle_true", "Zur LV-Kontrolle: Ja"),
                            ("zur_lv_kontrolle_false", "Zur LV-Kontrolle: Nein"),
                            ("ki_beteiligung_true", "KI-Beteiligung: Ja"),
                            ("ki_beteiligung_false", "KI-Beteiligung: Nein"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "phrase_text",
                    models.CharField(
                        help_text="Die exakte Phrase, nach der im Text gesucht wird.",
                        max_length=200,
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="global_phrases",
                        to="core.anlage2config",
                    ),
                ),
            ],
            options={
                "ordering": ["phrase_type", "phrase_text"],
            },
        ),
    ]
