# Generated by Django 5.2.4 on 2025-07-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_remove_involvement_justification_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="funktionsergebnis",
            name="ki_beteiligt_begruendung",
            field=models.TextField(blank=True, null=True),
        ),
    ]
