# Generated by Django 5.2.4 on 2025-07-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_funktionsergebnis_ki_beteiligt_begruendung"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="gap_notiz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="gap_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
