# Generated by Django 5.2 on 2025-06-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_anlage2globalphrase"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2config",
            name="enforce_subquestion_override",
            field=models.BooleanField(
                default=False,
                help_text="Wenn aktiviert, wird eine Hauptfunktion automatisch als 'technisch vorhanden' markiert, wenn mindestens eine ihrer Unterfragen als 'technisch vorhanden' bewertet wird.",
            ),
        ),
    ]
