# Generated by Django 5.2.3 on 2025-06-14 00:00

from django.db import migrations


def add_prompt(apps, schema_editor):
    Prompt = apps.get_model("core", "Prompt")
    Prompt.objects.get_or_create(
        name="anlage2_feature_justification",
        defaults={
            "text": (
                "Warum besitzt die Software '{software_name}' typischerweise die "
                "Funktion oder Eigenschaft '{function_name}'?"
            ),
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_anlage2config_enforce_subquestion_override"),
    ]

    operations = [
        migrations.RunPython(add_prompt, migrations.RunPython.noop),
    ]
