# Generated by Django 5.2.3 on 2025-07-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_add_gap_fields_to_projectfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funktionsergebnis',
            name='gap_begruendung_extern',
        ),
        migrations.RemoveField(
            model_name='funktionsergebnis',
            name='gap_begruendung_intern',
        ),
        migrations.AlterField(
            model_name='anlage2config',
            name='parser_order',
            field=models.JSONField(default=list, help_text='Reihenfolge der zu verwendenden Parser.'),
        ),
        migrations.AlterField(
            model_name='bvproject',
            name='classification_json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Klassifizierung'),
        ),
        migrations.AlterField(
            model_name='bvprojectfile',
            name='analysis_json',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Analyse'),
        ),
        migrations.AlterField(
            model_name='bvprojectfile',
            name='manual_analysis_json',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='bvprojectfile',
            name='question_review',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='bvprojectfile',
            name='verification_json',
            field=models.JSONField(blank=True, default=dict, help_text='Ergebnis der KI-gestützten Verifizierung der Funktionen.', null=True),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='available_models',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
