# Generated by Django 5.2.3 on 2025-06-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_add_feature_justification_prompt"),
        ("core", "0050_feature_justification_prompt"),
    ]

    operations = []
