# Generated by Django 5.2.4 on 2025-07-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_anlage2config_parser_order_and_more"),
        ("core", "0051_remove_gap_prompt_fields"),
    ]

    operations = []
