# Generated by Django 5.2.3 on 2025-06-15 21:53

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_merge_20250613_2352"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=50, unique=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("is_done_status", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["ordering", "name"],
            },
        ),
        migrations.RenameField(
            model_name="bvproject",
            old_name="status",
            new_name="status_old",
        ),
        migrations.RenameField(
            model_name="bvprojectstatushistory",
            old_name="status",
            new_name="status_old",
        ),
        migrations.AddField(
            model_name="bvproject",
            name="status",
            field=models.ForeignKey(
                to="core.projectstatus",
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
                related_name="projects",
            ),
        ),
        migrations.AddField(
            model_name="bvprojectstatushistory",
            name="status",
            field=models.ForeignKey(
                to="core.projectstatus",
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
            ),
        ),
    ]
