# Generated by Django 5.2.1 on 2025-06-15 21:41

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_migrate_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bvprojectstatushistory',
            name='status',
            field=models.ForeignKey(default=core.models.get_default_project_status, on_delete=django.db.models.deletion.PROTECT, to='core.projectstatus'),
        ),
    ]
