# Generated by Django 5.2.3 on 2025-06-15 21:53

from django.db import migrations


STATUS_CHOICES_OLD = [
    ("NEW", "Neu"),
    ("CLASSIFIED", "Klassifiziert"),
    ("GUTACHTEN_OK", "Gutachten OK"),
    ("GUTACHTEN_FREIGEGEBEN", "Gutachten freigegeben"),
    ("IN_PRUEFUNG_ANLAGE_X", "In Pr\u00fcfung Anlage X"),
    ("FB_IN_PRUEFUNG", "FB in Pr\u00fcfung"),
    ("ENDGEPRUEFT", "Endgepr\u00fcft"),
]


def forwards_func(apps, schema_editor):
    ProjectStatus = apps.get_model("core", "ProjectStatus")
    BVProject = apps.get_model("core", "BVProject")
    History = apps.get_model("core", "BVProjectStatusHistory")

    for idx, (key, name) in enumerate(STATUS_CHOICES_OLD, start=1):
        ProjectStatus.objects.create(
            key=key,
            name=name,
            ordering=idx,
            is_default=key == "NEW",
            is_done_status=key == "ENDGEPRUEFT",
        )

    for project in BVProject.objects.all():
        status_obj = ProjectStatus.objects.get(key=project.status_old)
        project.status = status_obj
        project.save(update_fields=["status"])

    for entry in History.objects.all():
        status_obj = ProjectStatus.objects.get(key=entry.status_old)
        entry.status = status_obj
        entry.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_projectstatus_alter_bvproject_status_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
