# Generated by Django 5.2.3 on 2025-06-15 21:54

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_populate_status_foreignkey"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bvproject",
            name="status_old",
        ),
        migrations.RemoveField(
            model_name="bvprojectstatushistory",
            name="status_old",
        ),
        migrations.AlterField(
            model_name="bvprojectstatushistory",
            name="status",
            field=models.ForeignKey(
                default=core.models.get_default_project_status,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.projectstatus",
            ),
        ),
    ]
