# Generated by Django 5.2 on 2025-06-17 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_softwaretype_gutachten"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gutachten",
            name="project",
        ),
        migrations.RemoveField(
            model_name="gutachten",
            name="software_type",
        ),
        migrations.AddField(
            model_name="gutachten",
            name="software_knowledge",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gutachten",
                to="core.softwareknowledge",
            ),
            preserve_default=False,
        ),
    ]
