# Generated by Django 5.2.3 on 2025-06-18 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_remove_gutachten_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ein kurzer, wiedererkennbarer Name für die Rolle.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "role_prompt",
                    models.TextField(
                        help_text="Der eigentliche System-Prompt, der die Persona und Anweisungen für die KI definiert."
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Soll diese Rolle als globaler Standard verwendet werden, wenn einem Prompt keine spezifische Rolle zugewiesen ist?",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prompt",
            name="role",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionale, spezifische Rolle für diesen Prompt. Überschreibt die globale Standard-Rolle.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.llmrole",
            ),
        ),
    ]
