# Generated by Django 5.2.3 on 2025-06-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_remove_obsolete_anlage1_prompts"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="use_system_role",
            field=models.BooleanField(
                default=True,
                help_text="Wenn aktiviert, wird diesem Prompt der globale oder zugewiesene Rollen-Prompt vorangestellt. Deaktivieren für einfache Abfragen, die eine strikte, kurze Antwort erfordern.",
            ),
        ),
    ]
