# Generated by Django 5.2.3 on 2025-06-18 18:48

from django.db import migrations


def forwards_func(apps, schema_editor):
    Prompt = apps.get_model('core', 'Prompt')
    Prompt.objects.filter(name='check_anlage2').delete()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_initial_check_prompts"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
