# Generated by Django 5.2.3 on 2025-06-23 13:21

from django.db import migrations

PROMPT_KEY = "initial_check_knowledge_with_context"
PROMPT_TEXT = (
    "Kennst du die Software '{name}'? Hier ist zusätzlicher Kontext, um sie zu "
    'identifizieren: "{user_context}". Antworte ausschließlich mit einem eini'
    "gen Wort: 'Ja' oder 'Nein'."
)


def forwards_func(apps, schema_editor):
    Prompt = apps.get_model('core', 'Prompt')
    Prompt.objects.get_or_create(name=PROMPT_KEY, defaults={'text': PROMPT_TEXT})


def reverse_func(apps, schema_editor):
    Prompt = apps.get_model('core', 'Prompt')
    Prompt.objects.filter(name=PROMPT_KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0064_feature_verification_prompt_no_system_role"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
