# Generated by Django 5.2.3 on 2025-06-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_add_context_knowledge_prompt"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SoftwareType",
        ),
    ]
