# Generated by Django 5.2.2 on 2025-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_update_prompt_texts"),
    ]

    def forwards_func(apps, schema_editor):
        Tile = apps.get_model("core", "Tile")
        for tile in Tile.objects.all():
            if hasattr(tile, "bereich_id") and tile.bereich_id:
                tile.areas.add(tile.bereich_id)

    operations = [
        migrations.AddField(
            model_name="tile",
            name="areas",
            field=models.ManyToManyField(
                help_text="Die Bereiche, in denen diese Kachel angezeigt wird.",
                related_name="tiles",
                to="core.area",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tile",
            name="bereich",
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(
                help_text="Einzigartiger Name des Bereichs, z.B. 'work' oder 'personal'",
                max_length=100,
                unique=True,
            ),
        ),
    ]
