# Generated by Django 5.2.3 on 2025-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_convert_software_typen_to_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bvproject",
            name="software_typen",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Software-Typen"
            ),
        ),
    ]
