# Generated by Django 4.2.11 on 2025-06-25 20:40

from django.db import migrations

PROMPTS_TO_ADD = [
    {
        "key": "anlage2_subquestion_verification",
        "prompt_text": (
            "Antworte ausschließlich mit 'Ja' oder 'Nein'. Frage: Ist die Software '{software_name}' typischerweise in der Lage, die folgende spezifische Anforderung zu erfüllen: '{subquestion_text}'?"
        ),
    },
    {
        "key": "anlage2_subquestion_justification",
        "prompt_text": (
            "Gib eine kurze Begründung, warum die Software '{software_name}' die Anforderung '{subquestion_text}' erfüllen kann."
        ),
    },
]


def forwards_func(apps, schema_editor):
    Prompt = apps.get_model("core", "Prompt")
    for prompt_data in PROMPTS_TO_ADD:
        Prompt.objects.get_or_create(
            name=prompt_data["key"],
            defaults={"text": prompt_data["prompt_text"]},
        )


def reverse_func(apps, schema_editor):
    Prompt = apps.get_model("core", "Prompt")
    keys_to_delete = [p["key"] for p in PROMPTS_TO_ADD]
    Prompt.objects.filter(name__in=keys_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_remove_tile_bereich_tile_areas_alter_area_name"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
