# Generated by Django 5.2.2 on 2025-06-25 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_remove_tile_bereich_tile_areas_alter_area_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bvproject",
            name="software_typen",
        ),
        migrations.CreateModel(
            name="BVSoftware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "projekt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.bvproject"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
