# Generated by Django 5.2.3 on 2025-06-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_add_bvsoftware_remove_field'),
        ('core', '0069_add_subquestion_verification_prompts'),
        ('core', '0070_user_area_access'),
    ]

    operations = [
    ]
