# Generated by Django 5.2.3 on 2025-06-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_merge_20250625_2306"),
    ]

    operations = [
        migrations.AddField(
            model_name="bvprojectfile",
            name="manual_reviewed",
            field=models.BooleanField(default=False, verbose_name="Manuell geprüft"),
        ),
        migrations.AddField(
            model_name="bvprojectfile",
            name="verhandlungsfaehig",
            field=models.BooleanField(default=False, verbose_name="Verhandlungsfähig"),
        ),
    ]
