# Generated by Django 5.2.3 on 2025-06-27 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_add_vision_model_and_prompt"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anlage3VisionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("geeignetheit", models.TextField(blank=True)),
                ("erforderlichkeit", models.TextField(blank=True)),
                ("verhaeltnismaessigkeit", models.TextField(blank=True)),
                ("hinweise", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.bvprojectfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
