# Generated by Django 5.2.3 on 2025-06-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_update_check_anlage3_vision_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2config",
            name="text_einsatz_telefonica_false",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_einsatz_telefonica_true",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_ki_beteiligung_false",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_ki_beteiligung_true",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_technisch_verfuegbar_false",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_technisch_verfuegbar_true",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_zur_lv_kontrolle_false",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="text_zur_lv_kontrolle_true",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
