# Generated by Django 5.2.3 on 2025-06-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_add_text_phrase_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2config",
            name="parser_mode",
            field=models.CharField(
                choices=[
                    ("auto", "Automatisch"),
                    ("table_only", "Nur Tabellen"),
                    ("text_only", "Nur Text"),
                ],
                default="auto",
                max_length=20,
            ),
        ),
    ]
