# Generated by Django 5.2.3 on 2025-07-02 12:00
from django.db import migrations
import json


def convert_value(val):
    if val is None or val == "":
        return []
    if isinstance(val, list):
        return val
    if isinstance(val, str):
        text = val.strip()
        if not text:
            return []
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            parsed = None
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, str):
            return [parsed]
        return [line.strip() for line in text.splitlines() if line.strip()]
    return [str(val)]


def forwards_func(apps, schema_editor):
    Config = apps.get_model("core", "Anlage2Config")
    fields = [
        "text_technisch_verfuegbar_true",
        "text_technisch_verfuegbar_false",
        "text_einsatz_telefonica_true",
        "text_einsatz_telefonica_false",
        "text_zur_lv_kontrolle_true",
        "text_zur_lv_kontrolle_false",
        "text_ki_beteiligung_true",
        "text_ki_beteiligung_false",
    ]
    for cfg in Config.objects.all():
        updated = False
        for field in fields:
            val = getattr(cfg, field)
            new_val = convert_value(val)
            if new_val != val:
                setattr(cfg, field, new_val)
                updated = True
        if updated:
            cfg.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0076_add_parser_mode_field"),
    ]

    operations = [
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
