# Generated by Django 5.2.3 on 2025-06-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_add_parser_mode_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anlage2function',
            name='detection_phrases',
            field=models.JSONField(blank=True, default=dict, help_text='Liste der Erkennungsphrasen für den Text-Parser.'),
        ),
        migrations.AlterField(
            model_name='anlage2subquestion',
            name='detection_phrases',
            field=models.JSONField(blank=True, default=dict, help_text='Liste der Erkennungsphrasen für den Text-Parser.'),
        ),
    ]
