# Generated by Django 5.2 on 2025-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_remove_text_parser"),
    ]

    operations = [
        migrations.AddField(
            model_name="anlage2config",
            name="default_parser",
            field=models.CharField(
                choices=[("table", "Tabellen-Parser")],
                default="table",
                help_text="Bevorzugter Parser für Anlage 2.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="anlage2config",
            name="fallback_parser",
            field=models.CharField(
                blank=True,
                choices=[("table", "Tabellen-Parser")],
                help_text="Optionaler Fallback-Parser, falls der erste kein Ergebnis liefert.",
                max_length=50,
            ),
        ),
    ]
