# Generated by Django 5.0 on 2025-06-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_alter_anlage2config_text_einsatz_telefonica_false_and_more"),
        ("core", "0080_replace_parser_fields"),
    ]

    operations = []
