from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("work/", views.work, name="work"),
    path("personal/", views.personal, name="personal"),
    path("account/", views.account, name="account"),
    path("recording/<str:bereich>/", views.recording_page, name="recording_page"),
    path(
        "start-recording/<str:bereich>/",
        views.start_recording_view,
        name="start_recording",
    ),
    path(
        "stop-recording/<str:bereich>/",
        views.stop_recording_view,
        name="stop_recording",
    ),
    path(
        "toggle-recording/<str:bereich>/",
        views.toggle_recording_view,
        name="toggle_recording",
    ),
    path("upload/", views.upload_recording, name="upload_recording"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("upload-transcript/", views.upload_transcript, name="upload_transcript"),
    path(
        "personal/talkdiary/",
        views.talkdiary,
        {"bereich": "personal"},
        name="talkdiary_personal",
    ),
    path(
        "work/talkdiary/", views.talkdiary, {"bereich": "work"}, name="talkdiary_work"
    ),
    path("talkdiary/<int:pk>/", views.talkdiary_detail, name="talkdiary_detail"),
    path(
        "transcribe/<int:pk>/", views.transcribe_recording, name="transcribe_recording"
    ),
    path("recording/delete/<int:pk>/", views.recording_delete, name="recording_delete"),
    path("talkdiary-admin/", views.admin_talkdiary, name="admin_talkdiary"),
    path(
        "admin/config-transfer/",
        views.config_export_import_view,
        name="config_transfer",
    ),
    path("projects-admin/", views.admin_projects, name="admin_projects"),
    path(
        "projects-admin/export/",
        views.admin_project_export,
        name="admin_project_export",
    ),
    path(
        "projects-admin/import/",
        views.admin_project_import,
        name="admin_project_import",
    ),
    path("projects-admin/statuses/", views.admin_project_statuses, name="admin_project_statuses"),
    path("projects-admin/statuses/new/", views.admin_project_status_form, name="admin_project_status_new"),
    path("projects-admin/statuses/<int:pk>/edit/", views.admin_project_status_form, name="admin_project_status_edit"),
    path("projects-admin/statuses/<int:pk>/delete/", views.admin_project_status_delete, name="admin_project_status_delete"),
    path("projects-admin/statuses/export/", views.admin_project_status_export, name="admin_project_status_export"),
    path("projects-admin/statuses/import/", views.admin_project_status_import, name="admin_project_status_import"),
    path("projects-admin/roles/", views.admin_llm_roles, name="admin_llm_roles"),
    path("projects-admin/roles/new/", views.admin_llm_role_form, name="admin_llm_role_new"),
    path("projects-admin/roles/<int:pk>/edit/", views.admin_llm_role_form, name="admin_llm_role_edit"),
    path("projects-admin/roles/<int:pk>/delete/", views.admin_llm_role_delete, name="admin_llm_role_delete"),
    path("projects-admin/llm-roles/export/", views.admin_llm_role_export, name="admin_llm_role_export"),
    path("projects-admin/llm-roles/import/", views.admin_llm_role_import, name="admin_llm_role_import"),
    path(
        "projects-admin/<int:pk>/delete/",
        views.admin_project_delete,
        name="admin_project_delete",
    ),
    path(
        "projects-admin/<int:pk>/cleanup/",
        views.admin_project_cleanup,
        name="admin_project_cleanup",
    ),
    path("projects-admin/prompts/", views.admin_prompts, name="admin_prompts"),
    path(
        "projects-admin/prompts/export/",
        views.admin_prompt_export,
        name="admin_prompt_export",
    ),
    path(
        "projects-admin/prompts/import/",
        views.admin_prompt_import,
        name="admin_prompt_import",
    ),
    path("projects-admin/models/", views.admin_models, name="admin_models"),
    path("projects-admin/users/", views.admin_user_list, name="admin_user_list"),
    path(
        "projects-admin/users/export/",
        views.admin_export_users_permissions,
        name="admin_export_users_permissions",
    ),
    path(
        "projects-admin/users/import/",
        views.admin_import_users_permissions,
        name="admin_import_users_permissions",
    ),
    path(
        "projects-admin/users/<int:user_id>/permissions/",
        views.admin_edit_user_permissions,
        name="admin_edit_user_permissions",
    ),
    path(
        "projects-admin/roles-editor/",
        views.admin_role_editor,
        name="admin_role_editor",
    ),
    path("projects-admin/anlage1/", views.admin_anlage1, name="admin_anlage1"),
    path(
        "projects-admin/anlage1/export/",
        views.admin_anlage1_export,
        name="admin_anlage1_export",
    ),
    path(
        "projects-admin/anlage1/import/",
        views.admin_anlage1_import,
        name="admin_anlage1_import",
    ),
    path(
        "projects-admin/anlage2/config/",
        views.anlage2_config,
        name="anlage2_config",
    ),
    path(
        "projects-admin/anlage4/config/",
        views.anlage4_config,
        name="anlage4_config",
    ),
    path(
        "projects-admin/anlage2-config/export/",
        views.admin_anlage2_config_export,
        name="admin_anlage2_config_export",
    ),
    path(
        "projects-admin/anlage2-config/import/",
        views.admin_anlage2_config_import,
        name="admin_anlage2_config_import",
    ),
    path(
        "projects-admin/anlage2/rules/add/",
        views.anlage2_rule_add,
        name="anlage2_rule_add",
    ),
    path(
        "projects-admin/anlage2/rules/<int:pk>/delete/",
        views.anlage2_rule_delete,
        name="anlage2_rule_delete",
    ),
    path(
        "projects-admin/parser-rules/",
        views.AntwortErkennungsRegelListView.as_view(),
        name="parser_rule_list",
    ),
    path(
        "projects-admin/parser-rules/add/",
        views.AntwortErkennungsRegelCreateView.as_view(),
        name="parser_rule_add",
    ),
    path(
        "projects-admin/parser-rules/<int:pk>/edit/",
        views.AntwortErkennungsRegelUpdateView.as_view(),
        name="parser_rule_edit",
    ),
    path(
        "projects-admin/parser-rules/<int:pk>/delete/",
        views.AntwortErkennungsRegelDeleteView.as_view(),
        name="parser_rule_delete",
    ),
    path(
        "projects-admin/parser-rules/export/",
        views.anlage2_parser_rule_export,
        name="anlage2_parser_rule_export",
    ),
    path(
        "projects-admin/parser-rules/import/",
        views.anlage2_parser_rule_import,
        name="anlage2_parser_rule_import",
    ),
    path(
        "projects-admin/anlage3/rules/",
        views.Anlage3ParserRuleListView.as_view(),
        name="anlage3_rule_list",
    ),
    path(
        "projects-admin/anlage3/rules/add/",
        views.Anlage3ParserRuleCreateView.as_view(),
        name="anlage3_rule_add",
    ),
    path(
        "projects-admin/anlage3/rules/<int:pk>/edit/",
        views.Anlage3ParserRuleUpdateView.as_view(),
        name="anlage3_rule_edit",
    ),
    path(
        "projects-admin/anlage3/rules/<int:pk>/delete/",
        views.Anlage3ParserRuleDeleteView.as_view(),
        name="anlage3_rule_delete",
    ),
    path(
        "projects-admin/anlage2/",
        views.anlage2_function_list,
        name="anlage2_function_list",
    ),
    path(
        "projects-admin/anlage2/new/",
        views.anlage2_function_form,
        name="anlage2_function_new",
    ),
    path(
        "projects-admin/anlage2/<int:pk>/edit/",
        views.anlage2_function_form,
        name="anlage2_function_edit",
    ),
    path(
        "projects-admin/anlage2/<int:pk>/delete/",
        views.anlage2_function_delete,
        name="anlage2_function_delete",
    ),
    path(
        "projects-admin/anlage2/import/",
        views.anlage2_function_import,
        name="anlage2_function_import",
    ),
    path(
        "projects-admin/anlage2/export/",
        views.anlage2_function_export,
        name="anlage2_function_export",
    ),
    path(
        "projects-admin/anlage2/<int:function_pk>/subquestion/new/",
        views.anlage2_subquestion_form,
        name="anlage2_subquestion_new",
    ),
    path(
        "projects-admin/anlage2/subquestion/<int:pk>/edit/",
        views.anlage2_subquestion_form,
        name="anlage2_subquestion_edit",
    ),
    path(
        "projects-admin/anlage2/subquestion/<int:pk>/delete/",
        views.anlage2_subquestion_delete,
        name="anlage2_subquestion_delete",
    ),
    path("projects-admin/purposes/", views.ZweckKategorieAListView.as_view(), name="zweckkategoriea_list"),
    path("projects-admin/purposes/add/", views.ZweckKategorieACreateView.as_view(), name="zweckkategoriea_add"),
    path("projects-admin/purposes/<int:pk>/edit/", views.ZweckKategorieAUpdateView.as_view(), name="zweckkategoriea_edit"),
    path("projects-admin/purposes/<int:pk>/delete/", views.ZweckKategorieADeleteView.as_view(), name="zweckkategoriea_delete"),
    path("projects-admin/supervision-notes/", views.SupervisionNoteListView.as_view(), name="supervisionnote_list"),
    path("projects-admin/supervision-notes/add/", views.SupervisionNoteCreateView.as_view(), name="supervisionnote_add"),
    path("projects-admin/supervision-notes/<int:pk>/edit/", views.SupervisionNoteUpdateView.as_view(), name="supervisionnote_edit"),
    path("projects-admin/supervision-notes/<int:pk>/delete/", views.SupervisionNoteDeleteView.as_view(), name="supervisionnote_delete"),
    path("work/projekte/", views.projekt_list, name="projekt_list"),
    path("work/projekte/neu/", views.projekt_create, name="projekt_create"),
    path("work/projekte/<int:pk>/", views.projekt_detail, name="projekt_detail"),
    path("work/projekte/<int:pk>/bearbeiten/", views.projekt_edit, name="projekt_edit"),
    path(
        "work/projekte/<int:pk>/context/",
        views.edit_project_context,
        name="edit_project_context",
    ),
    path(
        "work/projekte/<int:pk>/anlage/",
        views.projekt_file_upload,
        name="projekt_file_upload",
    ),
    path(
        "work/projekte/<int:pk>/status/",
        views.projekt_status_update,
        name="projekt_status_update",
    ),
    path(
        "work/projekte/<int:pk>/functions-check/",
        views.projekt_functions_check,
        name="projekt_functions_check",
    ),
    path(
        "work/projekte/<int:projekt_id>/anlage2/supervision/",
        views.anlage2_supervision,
        name="anlage2_supervision",
    ),
    path(
        "work/anlage/<int:pk>/verify-feature/",
        views.anlage2_feature_verify,
        name="anlage2_feature_verify",
    ),
    path(
        "work/anlage/file/<int:file_id>/justification/<path:function_key>/",
        views.justification_detail_edit,
        name="justification_detail_edit",
    ),
    path(
        "work/anlage/file/<int:file_id>/involvement/<path:function_key>/",
        views.ki_involvement_detail_edit,
        name="ki_involvement_detail_edit",
    ),
    path(
        "work/anlage/file/<int:file_id>/justification/<path:function_key>/delete/",
        views.justification_delete,
        name="justification_delete",
    ),
    path(
        "work/anlage/<int:pk>/edit-ki-justification/",
        views.edit_ki_justification,
        name="edit_ki_justification",
    ),
    path(
        "ajax/task-status/<str:task_id>/",
        views.ajax_check_task_status,
        name="ajax_check_task_status",
    ),
    path(
        "ajax/save-manual-review-item/",
        views.ajax_save_manual_review_item,
        name="ajax_save_manual_review_item",
    ),
    path(
        "ajax/save-anlage2-review/",
        views.ajax_save_anlage2_review,
        name="ajax_save_anlage2_review",
    ),
    path(
        "hx/review-cell/<int:result_id>/<str:field_name>/",
        views.hx_update_review_cell,
        name="hx_update_review_cell",
    ),
    path(
        "hx/negotiable/<int:result_id>/",
        views.hx_toggle_negotiable,
        name="hx_toggle_negotiable",
    ),
    path(
        "hx/anlage1/toggle/<int:pk>/<int:num>/",
        views.hx_toggle_anlage1_ok,
        name="hx_toggle_anlage1_ok",
    ),
    path(
        "hx/anlage1/note/<int:pk>/<int:num>/<str:field>/",
        views.hx_anlage1_note,
        name="hx_anlage1_note",
    ),
    path(
        "hx/anlage/<int:pk>/toggle/<str:field>/",
        views.hx_toggle_project_file_flag,
        name="hx_toggle_project_file_flag",
    ),
    path(
        "hx/supervision/confirm/<int:result_id>/",
        views.hx_supervision_confirm,
        name="hx_supervision_confirm",
    ),
    path(
        "hx/supervision/notes/<int:result_id>/",
        views.hx_supervision_save_notes,
        name="hx_supervision_save_notes",
    ),
    path(
        "hx/supervision/add-note/<int:result_id>/",
        views.hx_supervision_add_standard_note,
        name="hx_supervision_add_standard_note",
    ),
    path(
        "hx/supervision/revert/<int:result_id>/",
        views.hx_supervision_revert_to_document,
        name="hx_supervision_revert_to_document",
    ),
    path(
        "hx_anlage_status/<int:pk>/",
        views.hx_anlage_status,
        name="hx_anlage_status",
    ),
    path(
        "hx_anlage_row/<int:pk>/",
        views.hx_anlage_row,
        name="hx_anlage_row",
    ),
    path(
        "hx/project/<int:pk>/anlage/<int:nr>/",
        views.hx_project_anlage_tab,
        name="hx_project_anlage_tab",
    ),
    path(
        "hx/project/<int:pk>/software/<str:tab>/",
        views.hx_project_software_tab,
        name="hx_project_software_tab",
    ),
    path(
        "hx/project/<int:pk>/upload/",
        views.hx_project_file_upload,
        name="hx_project_file_upload",
    ),
    path(
        "hx/project/<int:pk>/cockpit/",
        views.hx_project_cockpit,
        name="hx_project_cockpit",
    ),
    path(
        "anlage2/notizen/<int:result_id>/",
        views.edit_gap_notes,
        name="edit_gap_notes",
    ),
    path(
        "ajax/generate-gap-summary/<int:result_id>/",
        views.ajax_generate_gap_summary,
        name="ajax_generate_gap_summary",
    ),
    path(
        "ajax/start-gutachten/<int:project_id>/",
        views.ajax_start_gutachten_generation,
        name="ajax_start_gutachten_generation",
    ),
    path(
        "work/projekte/<int:pk>/anlage/<int:nr>/check/",
        views.projekt_file_check,
        name="projekt_file_check",
    ),
    path(
        "work/anlage/<int:pk>/check/",
        views.projekt_file_check_pk,
        name="projekt_file_check_pk",
    ),
    path(
        "work/anlage/<int:pk>/check-view/",
        views.projekt_file_check_view,
        name="projekt_file_check_view",
    ),
    path(
        "work/anlage/<int:pk>/parse/",
        views.projekt_file_parse_anlage2,
        name="projekt_file_parse_anlage2",
    ),
    path(
        "work/anlage/<int:pk>/trigger-analysis/",
        views.trigger_file_analysis,
        name="trigger_file_analysis",
    ),
    path(
        "work/anlage/<int:pk>/analyse4/",
        views.projekt_file_analyse_anlage4,
        name="projekt_file_analyse_anlage4",
    ),
    path(
        "work/anlage5/dummy/",
        views.anlage5_dummy,
        name="anlage5_dummy",
    ),
    path(
        "work/anlage6/<int:pk>/review/",
        views.anlage6_review,
        name="anlage6_review",
    ),
    path(
        "work/anlage4/<int:pk>/review/",
        views.anlage4_review,
        name="anlage4_review",
    ),
    path(
        "work/anlage3/<int:pk>/review/",
        views.anlage3_file_review,
        name="anlage3_file_review",
    ),
    path(
        "work/anlage5/<int:pk>/review/",
        views.anlage5_review,
        name="anlage5_review",
    ),
    path(
        "work/anlage/<int:pk>/edit-json/",
        views.projekt_file_edit_json,
        name="projekt_file_edit_json",
    ),
    path(
        "work/anlage/<int:pk>/compare/",
        views.compare_versions,
        name="compare_versions",
    ),
    path(
        "work/anlage/<int:pk>/delete-result/",
        views.projekt_file_delete_result,
        name="projekt_file_delete_result",
    ),
    path(
        "work/anlage/<int:pk>/delete-version/",
        views.delete_project_file_version,
        name="delete_project_file_version",
    ),
    path(
        "work/anlage/<int:pk>/reset-all-reviews/",
        views.ajax_reset_all_reviews,
        name="ajax_reset_all_reviews",
    ),
    path(
        "work/anlage/<int:pk>/toggle/<str:field>/",
        views.project_file_toggle_flag,
        name="project_file_toggle_flag",
    ),
    path(
        "work/projekte/<int:pk>/gap-analysis/",
        views.projekt_gap_analysis,
        name="projekt_gap_analysis",
    ),
    path(
        "work/projekte/<int:pk>/summary/",
        views.projekt_management_summary,
        name="projekt_management_summary",
    ),
    path(
        "work/projekte/<int:pk>/gap-report/",
        views.gap_report_view,
        name="gap_report_view",
    ),
    path(
        "work/projekte/<int:pk>/gap-report/delete/",
        views.delete_gap_report,
        name="delete_gap_report",
    ),
    path(
        "work/projekte/<int:pk>/anlage3-review/",
        views.anlage3_review,
        name="anlage3_review",
    ),
    path(
        "work/gutachten/<int:pk>/view/",
        views.gutachten_view,
        name="gutachten_view",
    ),
    path(
        "work/gutachten/<int:pk>/download/",
        views.gutachten_download,
        name="gutachten_download",
    ),
    path(
        "work/gutachten/<int:pk>/edit/",
        views.gutachten_edit,
        name="gutachten_edit",
    ),
    path(
        "work/gutachten/<int:pk>/delete/",
        views.gutachten_delete,
        name="gutachten_delete",
    ),
    path(
        "work/gutachten/<int:pk>/llm-check/",
        views.gutachten_llm_check,
        name="gutachten_llm_check",
    ),
    path("projects/<int:pk>/", views.project_detail_api, name="project_detail_api"),
    path(
        "ajax/start-initial-checks/<int:project_id>/",
        views.ajax_start_initial_checks,
        name="ajax_start_initial_checks",
    ),
    path(
        "ajax/rerun-initial-check/",
        views.ajax_rerun_initial_check,
        name="ajax_rerun_initial_check",
    ),
    path(
        "ajax/docx-preview/",
        views.ajax_docx_preview,
        name="ajax_docx_preview",
    ),
    path(
        "knowledge/<int:knowledge_id>/edit/",
        views.edit_knowledge_description,
        name="edit_knowledge_description",
    ),
    path(
        "knowledge/<int:knowledge_id>/delete/",
        views.delete_knowledge_entry,
        name="delete_knowledge_entry",
    ),
    path(
        "knowledge/<int:knowledge_id>/download/",
        views.download_knowledge_as_word,
        name="download_knowledge_as_word",
    ),
    path(
        "login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="login"), name="logout"),
]
